# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import oracle_pb2 as oracle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in oracle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OracleServiceStub(object):
    """Service for high-frequency oracle ingestion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTelemetry = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/SubmitTelemetry',
                request_serializer=oracle__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=oracle__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.SubmitTelemetryBatch = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/SubmitTelemetryBatch',
                request_serializer=oracle__pb2.TelemetryBatchRequest.SerializeToString,
                response_deserializer=oracle__pb2.TelemetryBatchResponse.FromString,
                _registered_method=True)
        self.PushGradients = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/PushGradients',
                request_serializer=oracle__pb2.PushGradientsRequest.SerializeToString,
                response_deserializer=oracle__pb2.PushGradientsResponse.FromString,
                _registered_method=True)
        self.PullGlobalModel = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/PullGlobalModel',
                request_serializer=oracle__pb2.PullGlobalModelRequest.SerializeToString,
                response_deserializer=oracle__pb2.PullGlobalModelResponse.FromString,
                _registered_method=True)


class OracleServiceServicer(object):
    """Service for high-frequency oracle ingestion
    """

    def SubmitTelemetry(self, request, context):
        """Path A: High-frequency telemetry ingestion (VPP operations)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTelemetryBatch(self, request, context):
        """Batch: Submit multiple telemetry readings in one call (high throughput)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushGradients(self, request, context):
        """Federated Learning: Push locally trained model gradients for global aggregation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullGlobalModel(self, request, context):
        """Federated Learning: Pull the latest global model weights (Gating/Experts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OracleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTelemetry,
                    request_deserializer=oracle__pb2.TelemetryRequest.FromString,
                    response_serializer=oracle__pb2.TelemetryResponse.SerializeToString,
            ),
            'SubmitTelemetryBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTelemetryBatch,
                    request_deserializer=oracle__pb2.TelemetryBatchRequest.FromString,
                    response_serializer=oracle__pb2.TelemetryBatchResponse.SerializeToString,
            ),
            'PushGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.PushGradients,
                    request_deserializer=oracle__pb2.PushGradientsRequest.FromString,
                    response_serializer=oracle__pb2.PushGradientsResponse.SerializeToString,
            ),
            'PullGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PullGlobalModel,
                    request_deserializer=oracle__pb2.PullGlobalModelRequest.FromString,
                    response_serializer=oracle__pb2.PullGlobalModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gridtokenx.oracle.v1.OracleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gridtokenx.oracle.v1.OracleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleService(object):
    """Service for high-frequency oracle ingestion
    """

    @staticmethod
    def SubmitTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/SubmitTelemetry',
            oracle__pb2.TelemetryRequest.SerializeToString,
            oracle__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTelemetryBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/SubmitTelemetryBatch',
            oracle__pb2.TelemetryBatchRequest.SerializeToString,
            oracle__pb2.TelemetryBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/PushGradients',
            oracle__pb2.PushGradientsRequest.SerializeToString,
            oracle__pb2.PushGradientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/PullGlobalModel',
            oracle__pb2.PullGlobalModelRequest.SerializeToString,
            oracle__pb2.PullGlobalModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
